### ISSUE TITLE
Console outputs to the wrong channel

### ISSUE THREAD

**Issue by sky-48** [SNH48Live/KVM48#6]
Minor issue, but KVM48 prints **informational** logs to `stderr` instead of `stdout`.

I was trying to invoke KVM48 from Node.js, and hooking up to `stdout` to observe outputs, but got nothing. I then added catches to see what sorts of error occurred, but surprised to find logs appearing in the error channel. After inspecting the source code of `kvm48.py`, I see many outputs are done using `sys.stderr.write` instead of `print`. `Standard Error` channel should be reserved to log errors.

**Comment by sky-48** [comment]
Actually I see `sys.stderr.write` and `print` being used in mix, but I don't seem to see the pattern. Maybe you had a logical way of separating outputs to different channels?

**Comment by zmwangx** [comment]
Hmm, you might have the wrong understanding of stdout and stderr.

Standard output is for *output*, which is generally somewhat structured to be parseable by other programs (so you could easily pipe and process — that's the third principle of the Unix philosophy). In the case of KVM48, output contains lines of tab delimited URLs and (relative) download paths, and optionally an asterisk as the new VOD indicator.

On the other hand, standard error, despite the name, is not only meant for errors. All messages and logs should go to stderr, regardless of level. Informational logs are generally of level INFO (sometimes DEBUG), and they are treated the same as WARNING, ERROR, and CRITICAL. If messages and logs are written to stdout, stdout becomes useless and you might as well just use one stream.

To show what I said is the norm, I'll observe two things (appealing to authority here): (1) Python's `logging.StreamHandler` logs to stderr by default (regardless of level, of course); (2) On most *nix operating systems, by default stdout is buffered, while stderr is unbuffered; of course informational messages go to the unbuffered stream since you want to see progress and stuff in real time.

Now, when I first wrote KVM48, instead of setting up logging proper, I cheaped out and littered `sys.stderr.write` everywhere. (See [caterpillar](https://github.com/zmwangx/caterpillar/), the dependency for m3u8 downloads, where I didn't cheap out and did the right thing.) That's unfortunate, but I'm always careful with writing to the correct stream.

I know many people these days get the streams wrong; I find this particularly prevalent among command line tools written in Node by web developers, where they dump all the crap to stdout, possibly because `console.error` sounds prohibitive. But I've lived and breathed Unix shells for long enough to know the right way, or at least form a strong opinion.

**Comment by zmwangx** [comment]
Oh what a coincidence. In fact, only after I posted the comment above did I notice the "I was trying to invoke KVM48 from Node.js" part... And I mentioned Node community as the worst offender. So yeah, Node people handle standard streams wrong all the time; if that's what you've mostly been exposed to, you might need to spend more time with more native command line tools. (Please don't take this personally.)

**Comment by sky-48** [comment]
Thank you for the clarification. I stand corrected.
